from sage.all import *

x,y,z,r,o,x_,y_,z_,r_,o_,o__,t=var('x,y,z,r,o,x_,y_,z_,r_,o_,o__,t')
x=function('x')(t)
y=function('y')(t)
z=function('z')(t)
r=function('r')(t)
o=function('o')(t)
r=((1/sqrt(x**2+y**2))*vector([x,y,0]))
o=((1/sqrt(x**2+y**2))*vector([x,y,0]))
x_=diff(x,t)
y_=diff(y,t)
z_=diff(z,t)
r_=simplify(diff(r,t))
o_=diff(o,t)
o__=diff(o_,t)
rr_=r.cross_product(r_)
print(r_)
print(o_)
